### PR TITLE
Fixed pathing issue with generated reports and PDF Report now loads in a popup dialog with an iframe.

### PR DESCRIPTION
**Pull request by justinnichols**

### CODE REVIEW

**Comment by justinnichols** [comment]
Can discuss further on playframework Google Group, but effectively this allows the pathing to the generated reports to work.

**Comment by HannahJSwystun** [comment]
Hi Justin it works before...But I am trying to open HTML Reports without EMBEDDING images...well i m going to try your commits and return to you soon as possible
thank you so so so much dear Justin

**Comment by HannahJSwystun** [comment]
I am going to try if HTML reports are generated without emebedding
images....let's see ;)

2016-07-18 18:06 GMT+00:00 Justin Nichols notifications@github.com:

**Comment by HannahJSwystun** [comment]
Hi,

I saw files changed!! could you commit your changes please?

2016-07-18 22:16 GMT+00:00 Hannah J Swystun j2eealidev@gmail.com:

**Comment by justinnichols** [comment]
Hannah,

I've committed as a pull request which means if you like the changes, you can merge them into your code base by clicking the merge button near the top of this pull request.

However, this only includes the fix to the directories not existing for the generated report.  It did not include referencing images without embedding.  Keep in mind, in the generated document the images will have to be embedded in the output file (PDF, excel, etc).  I will take a look to see if the source files can be simply on the filesystem and not embedded as you have done so.  My experience with Jasper is quite limited so I'm sorry if I'm unable to solve that one but I will give it a try and will let you know.

If I happen to get it set up as you need then I will commit a new pull request for that.  I may have some further questions but I need to re-read that whole Google Group thread to make sure I don't waste any of your time with questions already answered.

Thanks!

**Comment by HannahJSwystun** [comment]
Hi Justin,
Thank you so much to contribute to the Revolutionnary Computer Database
Sample :)
The merge has already be done.

2016-07-18 23:09 GMT+00:00 Justin Nichols notifications@github.com:

**Comment by justinnichols** [comment]
You didn't actually merge this pull request, so now it includes me adding the PDF Report into a popup with an iframe (it required making a GET call to create the file, which I know isn't RESTful, but it's the only way I know how to make the iframe work like this without referencing the file by path and instead using the response from the call).

So take a look at this to see if you like it.  I hope it helps.

**Comment by HannahJSwystun** [comment]
Hello Justin,

I am really thankful for all your helps for this specifics details about
computer database Sample...do you have an idea why the iframe is still
empty !!!
Does this have something with OS !! I am under WINDOWS..

Thank you in advance

2016-07-20 19:25 GMT+00:00 Justin Nichols notifications@github.com:

**Pull request merged**
